# Generated by Django 5.1.4 on 2026-05-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquiteturaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('versao', models.CharField(default='1.0.0', max_length=20)),
                ('data_levantamento', models.DateField()),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('linguagem', models.CharField(default='Python', max_length=50)),
                ('framework', models.CharField(default='Django REST Framework', max_length=100)),
                ('banco', models.CharField(default='PostgreSQL', max_length=50)),
                ('autenticacao', models.CharField(default='JWT', max_length=50)),
                ('padrao_api', models.CharField(default='REST', max_length=50)),
                ('frontend_fw', models.CharField(default='React 18', max_length=100)),
                ('build_tool', models.CharField(default='Vite', max_length=50)),
                ('estilizacao', models.CharField(default='Tailwind CSS', max_length=100)),
                ('estado_global', models.CharField(default='Zustand', max_length=100)),
                ('server_state', models.CharField(default='TanStack Query', max_length=100)),
                ('ambiente_deploy', models.CharField(default='VPS própria (Uid Software)', max_length=200)),
                ('servidor_web', models.CharField(default='Nginx', max_length=50)),
                ('docker', models.BooleanField(default=True)),
                ('ssl', models.BooleanField(default=True)),
                ('cicd', models.BooleanField(default=False)),
                ('pwa', models.BooleanField(default=False)),
                ('dominio_uid', models.BooleanField(default=False)),
                ('padrao_rotas', models.TextField(blank=True)),
                ('perfis_acesso', models.TextField(blank=True)),
                ('integracoes', models.TextField(blank=True)),
                ('restricoes', models.TextField(blank=True)),
                ('notas_claude', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arquitetura Técnica',
                'verbose_name_plural': 'Arquiteturas Técnicas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
