# Generated by Django 5.1.4 on 2026-06-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_create_entrevista'),
        ('prospectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquiteturatecnica',
            name='entrevista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arquiteturas', to='ordens.entrevista'),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='prospecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas', to='prospectos.prospecto'),
        ),
    ]
