# Generated by Django 5.1.4 on 2026-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0009_arquiteturatecnica_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='api_key_criada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='os',
            name='api_key_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 da chave de integração — a chave em si nunca é guardada em texto puro, só o hash (só dá pra ver o valor real uma vez, no momento em que é gerada).', max_length=64, null=True, unique=True, verbose_name='Hash da chave de API'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='disparada_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido automaticamente pelo disparar_hotfix.', null=True, verbose_name='Disparada em'),
        ),
    ]
