# Generated by Django 5.1.4 on 2026-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0013_entrevista_nicho'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquiteturatecnica',
            name='base_projeto',
            field=models.CharField(choices=[('ZERO', 'Do zero (stack padrão Uid)'), ('UIDCORE', 'Fork do UidCore (template multi-nicho)')], default='UIDCORE', max_length=20),
        ),
    ]
