# Generated by Django 5.1.4 on 2026-06-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('STACK_FORA_PADRAO', 'Stack fora do padrão'), ('IMPEDIMENTO_ESTEIRA', 'Impedimento na esteira'), ('LEAD_NAO_QUALIFICADO', 'Lead não qualificado'), ('PRONTO_PARA_PLANNER', 'Pronto para o Planner'), ('LIMITE_CLAUDE_ATIVO', 'Limite de uso do Claude ativo')], max_length=30),
        ),
    ]
