# Generated by Django 5.1.4 on 2026-07-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('levantamento_requisitos', 'Levantamento de Requisitos'), ('uml_usecase', 'UML — Casos de Uso'), ('uml_classes', 'UML — Classes'), ('uml_activity', 'UML — Atividades'), ('dicionario_dados', 'Dicionário de Dados'), ('regras_negocio', 'Regras de Negócio'), ('design_system', 'Design System'), ('adr', 'ADR'), ('especificacao_hotfix', 'Especificação de Hotfix'), ('especificacao_ui_hotfix', 'Especificação de UI (Hotfix)'), ('relatorio_qa', 'Relatório de QA'), ('deploy_info', 'Informações de Deploy'), ('outro', 'Outro')], max_length=30)),
                ('agente', models.CharField(choices=[('planner', 'Planner'), ('analista', 'Analista'), ('analista_uml', 'Analista UML'), ('blueprint', 'Blueprint'), ('brush', 'Brush'), ('doc_generator', 'Doc Generator'), ('forge', 'Forge'), ('loom', 'Loom'), ('sentinel', 'Sentinel'), ('pilot', 'Pilot'), ('hotfix', 'Hotfix')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(blank=True)),
                ('commit_hash', models.CharField(blank=True, max_length=40)),
                ('deploy_url', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Artefato',
                'verbose_name_plural': 'Artefatos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
