# Generated by Django 5.1.4 on 2026-07-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefato',
            name='tipo',
            field=models.CharField(choices=[('levantamento_requisitos', 'Levantamento de Requisitos'), ('uml_usecase', 'UML — Casos de Uso'), ('uml_classes', 'UML — Classes'), ('uml_activity', 'UML — Atividades'), ('uml_sequencia', 'UML — Sequência'), ('uml_estado', 'UML — Estado'), ('uml_componentes', 'UML — Componentes'), ('uml_implantacao', 'UML — Implantação'), ('dicionario_dados', 'Dicionário de Dados'), ('regras_negocio', 'Regras de Negócio'), ('design_system', 'Design System'), ('adr', 'ADR'), ('contrato_servico', 'Contrato de Serviço (documento)'), ('especificacao_hotfix', 'Especificação de Hotfix'), ('especificacao_ui_hotfix', 'Especificação de UI (Hotfix)'), ('relatorio_qa', 'Relatório de QA'), ('deploy_info', 'Informações de Deploy'), ('outro', 'Outro')], max_length=30),
        ),
    ]
