# Generated by Django 5.1.4 on 2026-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_dominio_email_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tem_entregas',
            field=models.BooleanField(default=False),
        ),
    ]
