# Generated by Django 5.1.4 on 2026-07-06 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_item_produto_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='emitido_em',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
