# Generated by Django 5.1.4 on 2026-08-23 22:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
