# Generated by Django 5.1.4 on 2026-05-25 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_tem_entregas'),
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Poupança'), ('CAIXA', 'Caixa'), ('CARTEIRA', 'Carteira Digital')], max_length=20)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_conta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('CAPITAL_SOCIAL', 'Capital Social'), ('SOCIO', 'Aporte de Sócio'), ('INVESTIDOR', 'Aporte de Investidor'), ('EMPRESTIMO', 'Empréstimo')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('responsavel', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes', to='financeiro.conta')),
            ],
            options={
                'db_table': 'fin_aporte',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável'), ('PROLABORE', 'Pró-labore'), ('IMPOSTO', 'Imposto / DAS'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
                ('referencia_mes', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, upload_to='despesas/')),
                ('observacoes', models.TextField(blank=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='financeiro.conta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_despesa',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='LivroCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('origem', models.CharField(choices=[('APORTE', 'Aporte'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('MANUAL', 'Lançamento Manual')], max_length=10)),
                ('origem_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estornado', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.conta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estorno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='financeiro.livrocaixa')),
            ],
            options={
                'db_table': 'fin_livro_caixa',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('ENTRADA_CONTRATO', 'Entrada de Contrato'), ('MENSALIDADE', 'Mensalidade'), ('CONSULTORIA', 'Consultoria Avulsa'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
                ('referencia_mes', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='clientes.cliente')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='financeiro.conta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='ordens.os')),
            ],
            options={
                'db_table': 'fin_receita',
                'ordering': ['vencimento'],
            },
        ),
    ]
