# Generated by Django 5.1.4 on 2026-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='tipo',
            field=models.CharField(choices=[('CAPITAL_SOCIAL', 'Capital Social'), ('SOCIO', 'Aporte do Fundador'), ('INVESTIDOR', 'Aporte de Investidor'), ('EMPRESTIMO', 'Empréstimo')], max_length=20),
        ),
    ]
