# Generated by Django 5.1.4 on 2026-05-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_add_forma_pagamento_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('TED_DOC', 'TED/DOC'), ('BOLETO', 'Boleto'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
