# Generated by Django 5.1.4 on 2026-05-27 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_add_forma_pagamento_despesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('forn_nome', models.CharField(max_length=200)),
                ('forn_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('forn_email', models.EmailField(blank=True, max_length=254)),
                ('forn_telefone', models.CharField(blank=True, max_length=20)),
                ('forn_observacoes', models.TextField(blank=True)),
                ('forn_ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_fornecedor',
                'ordering': ['forn_nome'],
            },
        ),
    ]
