# Generated by Django 5.1.4 on 2026-06-28 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_categoria_estorno_despesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrocaixa',
            name='origem',
            field=models.CharField(choices=[('APORTE', 'Aporte'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('MANUAL', 'Lançamento Manual'), ('TRANSFER', 'Transferência'), ('ESTORNO', 'Estorno')], max_length=10),
        ),
        migrations.CreateModel(
            name='ConciliacaoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('arquivo', models.CharField(max_length=500)),
                ('periodo', models.DateField()),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('COM_DIVERGENCIAS', 'Com Divergências')], default='PENDENTE', max_length=20)),
                ('total_banco', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('divergencias', models.IntegerField(default=0)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='financeiro.conta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_conciliacao_extrato',
                'ordering': ['-processado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_banco', models.DateField()),
                ('descricao_banco', models.CharField(max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('status', models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('FALTANDO_SISTEMA', 'Faltando no Sistema'), ('FALTANDO_BANCO', 'Faltando no Banco')], max_length=20)),
                ('confirmado', models.BooleanField(default=False)),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.conciliacaoextrato')),
                ('lancamento_lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to='financeiro.livrocaixa')),
            ],
            options={
                'db_table': 'fin_item_conciliacao',
                'ordering': ['data_banco'],
            },
        ),
    ]
