# Generated by Django 5.1.4 on 2026-08-03 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_pessoa_base_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='recorrencia_suspeita',
            field=models.CharField(blank=True, choices=[('ANUAL', 'Anual (suspeita)'), ('SEMESTRAL', 'Semestral (suspeita)'), ('TRIMESTRAL', 'Trimestral (suspeita)')], help_text='Recorrência não-mensal ainda não confirmada por repetição real (ex: imposto anual visto 1x).', max_length=20),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financeiro.categoria')),
            ],
            options={
                'db_table': 'fin_subcategoria',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='despesa',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='financeiro.subcategoria'),
        ),
        migrations.AddField(
            model_name='receita',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='financeiro.subcategoria'),
        ),
    ]
