# Generated by Django 5.1.4 on 2026-05-15 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_tem_entregas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ROTA', 'Em rota'), ('ENTREGUE', 'Entregue'), ('DEVOLVIDO', 'Devolvido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('confirmacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('NAO_CONFIRMADA', 'Não confirmada')], default='PENDENTE', max_length=20)),
                ('confirmacao_motivo', models.TextField(blank=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='clientes.cliente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-data', '-hora'],
            },
        ),
    ]
