# Generated by Django 5.1.4 on 2026-07-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_socio_cliente'),
        ('prospectos', '0002_socio_prospecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente já existente para o qual este prospecto representa um novo ciclo/projeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to='clientes.cliente'),
        ),
    ]
