# Generated by Django 5.1.4 on 2026-08-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0003_prospecto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='descricao_projeto',
            field=models.TextField(blank=True, help_text='Descrição da oportunidade/projeto — sobretudo quando este Prospecto não vem de um Lead (prospecção outbound), caso em que não há mensagem original de formulário pra herdar.'),
        ),
    ]
